development:
  settings:
    type: post
    process_on_start: false
    check_interval: 30 # in seconds

  rss_feeds:
    -
      url: http://localhost:3011/rss
      webhook: http://localhost:3011/hook
      output:
        room_id: 34343
        from: TMZ
        message: Body: #{title}
        color: green
        format: json
        
    -
      url: http://news.yahoo.com/rss/us
      webhook: http://localhost:3011/get_hook
      type: get