development:
  settings:
    type: post
    process_on_start: false
    check_interval: 10 # in seconds

  rss_feeds:
    -
      connection:
        host: secure3.silverorange.com
        ssl: true
        resource: /rsstest/httpauth/rss_with_ssl_and_auth.xml
        auth:
          username: testuser
          password: testpass

      webhook: http://localhost:3011/hook
      output:
        room_id: 34343
        from: TMZ
        message: Body is {title}
        color: green
        format: json
        
    -
      connection: http://news.yahoo.com/rss/us
      webhook: http://localhost:3011/get_hook
      type: get
      output:
        article:
          from: Yahoo! News
          title: {title}
          link: {link}